 SELECT a.posteam AS team,
    a.season,
    a.games,
    a.targets,
    a.targets_pg,
    a.tot_pass_yards,
    a.pass_yards_pg,
    a.tot_air_yards,
    a.air_yards_pg,
    a.racr,
    a.completions,
    a.adot,
    a.tot_pass_td,
    a.pass_td_pg,
    a.avg_cpoe,
    a.avg_pass_epa,
    a.tot_pass_epa,
    --defteam_passing
    b.targets_allowed,
    b.targets_allowed_pg,
    b.tot_pass_yards_allowed,
    b.pass_yards_allowed_pg,
    b.tot_air_yards_allowed,
    b.air_yards_allowed_pg,
    b.racr_allowed,
    b.completions_allowed,
    b.adot_allowed,
    b.tot_pass_td_allowed,
    b.pass_td_allowed_pg,
    b.avg_cpoe_allowed,
    b.avg_pass_epa_allowed,
    b.tot_pass_epa_allowed,
    --posteam_rushing
    c.rush_attempts,
    c.rush_attempts_pg,
    c.tot_rush_yards,
    c.rush_yards_pg,
    c.tot_rush_td,
    c.rush_td_pg,
    c.avg_rush_epa,
    c.tot_rush_epa,
    --defteam_rushing
    d.rushes_allowed,
    d.rush_attempts_allowed_pg,
    d.tot_rush_yards_allowed,
    d.rush_yards_allowed_pg,
    d.tot_rush_td_allowed,
    d.rush_td_allowed_pg,
    d.avg_rush_epa_allowed,
    d.tot_rush_epa_allowed
   FROM posteam_passing a
     LEFT JOIN defteam_passing b ON a.posteam = b.defteam AND a.season = b.season
     LEFT JOIN posteam_rushing c ON a.posteam = c.posteam AND a.season = c.season
     LEFT JOIN defteam_rushing d ON a.posteam = d.defteam AND a.season = d.season
  WHERE a.season::numeric = 2020.0;